//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GASLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purpose
    {
        public int PurposeId { get; set; }
        public string PurposeName { get; set; }
        public string PassportNo { get; set; }
        public System.DateTime Duration { get; set; }
    }
}
